CI/CD:
   name: CI/CD

   on:
     push:
       branches: [ main ]

   jobs:

     test:
       runs-on: ubuntu-latest
       
       steps:
       - uses: actions/checkout@v2
       - name: Use Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '14'
       
       - name: Install dependencies
         run: npm ci
       
       - name: Run tests
         run: npm test
         
     build:
       needs: test
       runs-on: ubuntu-latest
       
       steps:
       - uses: actions/checkout@v2
       
       - name: Build and push Docker image
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           tags: victoriamineeva/app:latest
           
     deploy:
       needs: build
       runs-on: ubuntu-latest
       
       steps:
       - name: Deploy to server
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: |
             docker pull user/app:latest
             docker stop myapp || true
             docker run -d --name myapp -p 8081:8081 user/app:latest
